import IconTechArduino from "./IconTechArduino.svg";
import IconTechCassandra from "./IconTechCassandra.svg";
import IconTechCss from "./IconTechCss.svg";
import IconTechEclipse from "./IconTechEclipse.svg";
import IconTechExpress from "./IconTechExpress.svg";
import IconTechFlask from "./IconTechFlask.svg";
import IconTechFigma from "./IconTechFigma.svg";
import IconTechGit from "./IconTechGit.svg";
import IconTechGithub from "./IconTechGithub.svg";
import IconTechHtml from "./IconTechHtml.svg";
import IconTechJava from "./IconTechJava.svg";
import IconTechJS from "./IconTechJS.svg";
import IconTechMongo from "./IconTechMongo.svg";
import IconTechMysql from "./IconTechMysql.svg";
import IconTechNodejs from "./IconTechNodejs.svg";
import IconTechPhotoshop from "./IconTechPhotoshop.svg";
import IconTechPostgres from "./IconTechPostgres.svg";
import IconTechPy from "./IconTechPy.svg";
import IconTechReact from "./IconTechReact.svg";
import IconTechRedis from "./IconTechRedis.svg";
import IconTechSpring from "./IconTechSpring.svg";
import IconTechTS from "./IconTechTS.svg";
import IconTechVercel from "./IconTechVercel.svg";
import IconTechVscode from "./IconTechVscode.svg";

export { IconTechArduino, IconTechCassandra, IconTechCss, IconTechEclipse, IconTechExpress, IconTechFigma, IconTechFlask, IconTechGit, IconTechGithub, IconTechHtml, IconTechJava, IconTechJS, IconTechMongo, IconTechMysql, IconTechNodejs, IconTechPhotoshop, IconTechPostgres, IconTechPy, IconTechReact, IconTechRedis, IconTechSpring, IconTechTS, IconTechVercel, IconTechVscode };